/* Generated by Yosys 0.9+3901 (git sha1 9f7cd10c, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module test(clock, reset, io_x, io_y, io_opcode, io_result);
  wire [15:0] _GEN_0;
  wire [15:0] _GEN_1;
  wire _T;
  wire [15:0] _T_2;
  wire _T_3;
  wire [15:0] _T_4;
  wire _T_5;
  wire [15:0] _T_6;
  wire [15:0] _T_8;
  input clock;
  input [1:0] io_opcode;
  output [15:0] io_result;
  input [15:0] io_x;
  input [15:0] io_y;
  input reset;
  assign _T_2 = io_x + io_y;
  assign _T_4 = io_x & io_y;
  assign _T_3 = io_opcode == 2'h2;
  assign _T_5 = io_opcode == 2'h3;
  assign _T = io_opcode == 1'h1;
  assign _T_6 = io_x | io_y;
  assign _T_8 = io_x - io_y;
  assign _GEN_0 = _T_5 ? _T_6 : _T_8;
  assign _GEN_1 = _T_3 ? _T_4 : _GEN_0;
  assign io_result = _T ? _T_2 : _GEN_1;
  assign _T = 1'h0;
endmodule
