all:
	yosys -m ../../build/libyosys_constraint_propagation.so run.ys

d:
	gdb --args yosys -m ../../build/libyosys_constraint_propagation.so run.ys

t:
	yosys -m ../../build/libyosys_constraint_propagation.so traverse.ys  
