/* Generated by Yosys 0.9+3901 (git sha1 9f7cd10c, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module decode(opcode, is_add, is_and, is_or);
  output is_add;
  output is_and;
  output is_or;
  input [1:0] opcode;
  assign is_or = opcode == 2'h3;
  assign is_add = opcode == 1'h1;
  assign is_and = opcode == 2'h2;
endmodule

module test(clock, reset, io_x, io_y, io_opcode, io_result);
  wire [15:0] _GEN_0;
  wire [15:0] _GEN_1;
  wire _T;
  wire [15:0] _T_2;
  wire _T_3;
  wire [15:0] _T_4;
  wire _T_5;
  wire [15:0] _T_6;
  wire [15:0] _T_8;
  input clock;
  input [1:0] io_opcode;
  output [15:0] io_result;
  input [15:0] io_x;
  input [15:0] io_y;
  input reset;
  assign _T_2 = io_x + io_y;
  assign _T_4 = io_x & io_y;
  assign _T_6 = io_x | io_y;
  assign _T_8 = io_x - io_y;
  assign _GEN_0 = _T_5 ? _T_6 : _T_8;
  assign _GEN_1 = _T_3 ? _T_4 : _GEN_0;
  assign io_result = _T ? _T_2 : _GEN_1;
  decode u0 (
    .is_add(_T),
    .is_and(_T_3),
    .is_or(_T_5),
    .opcode(io_opcode)
  );
endmodule
